### ISSUE TITLE
Getting OpenAI Error: Bad Request

### ISSUE THREAD

**Issue by NicolasIRAGNE** [Hi7cl4w/diffy-explain-ai#13]
Hello,

I am trying to get this to work but any command produces this error
![image](https://user-images.githubusercontent.com/16356420/220592212-66aadcef-f97a-4193-8891-ad37a6e442d1.png)

I am not sure where to get relevant logs 

Using vscode 1.75.1 on Windows 11

**Comment by NicolasIRAGNE** [comment]
The issue seems to not be there on my Linux machine. Interesting.

**Comment by Hi7cl4w** [comment]
issue resolved. update to version 0.0.15
