### ISSUE TITLE
Choosing the openai engine

### ISSUE THREAD

**Issue by ChocoTonic** [Hi7cl4w/diffy-explain-ai#18]
would it be possible to select a different engine, like the chat-gpt3.5 engine which is cheaper than the other engines?

**Comment by Hi7cl4w** [comment]
I am planning to do this feature future. certainly useful one.

**Comment by ChocoTonic** [comment]
is it still using davinci 2 right now?

**Comment by Hi7cl4w** [comment]
new version has an option to select models
